//###### Product#############

export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE"



// ######## AUTH ############################



export const AUTH_PRODUCT_REQUEST="AUTH_PRODUCT_REQUEST"
export const AUTH_PRODUCT_SUCCESS="AUTH_PRODUCT_SUCCESS"
export const AUTH_PRODUCT_FAILURE="AUTH_PRODUCT_FAILURE"