//###### Product#############
// GET DATA
export const POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAILURE="POST_PRODUCT_FAILURE"



// ######## AUTH ############################


// AUTH POST
export const AUTH_PRODUCT_REQUEST="AUTH_PRODUCT_REQUEST"
export const AUTH_PRODUCT_SUCCESS="AUTH_PRODUCT_SUCCESS"
export const AUTH_PRODUCT_FAILURE="AUTH_PRODUCT_FAILURE"

// FOR GET

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"